# -*- coding: utf-8 -*-
"""Revision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgmwmGVPcwJukNyu7pmf_aga95gmd90d
"""

from google.colab import drive
drive.mount('/content/drive')

# a) Import libraries and read dataset
print("\n----- (a) Import Libraries and Read Dataset -----")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Read dataset
df = pd.read_csv("/content/drive/MyDrive/Datasets/winequality.csv")

print("First five rows of the dataset:")
print(df.head())


# b) Identify data types and compute mean, median, mode
print("\n----- (b) Data Types and Central Tendency for Alcohol -----")

print("\nDataset Data Types:")
print(df.dtypes)

mean_alcohol = df['alcohol'].mean()
median_alcohol = df['alcohol'].median()
mode_alcohol = df['alcohol'].mode()[0]

print("Mean Alcohol:", mean_alcohol)
print("Median Alcohol:", median_alcohol)
print("Mode Alcohol:", mode_alcohol)


# c) Measures of variability
print("\n----- (c) Measures of Variability for Alcohol -----")

range_alcohol = df['alcohol'].max() - df['alcohol'].min()
iqr_alcohol = df['alcohol'].quantile(0.75) - df['alcohol'].quantile(0.25)
std_alcohol = df['alcohol'].std()
var_alcohol = df['alcohol'].var()

print("Range:", range_alcohol)
print("Inter Quartile Range (IQR):", iqr_alcohol)
print("Standard Deviation:", std_alcohol)
print("Variance:", var_alcohol)


# d) Histogram
print("\n----- (d) Histogram of Alcohol Distribution -----")

plt.figure()
plt.hist(df['alcohol'], bins=20)
plt.title("Distribution of Alcohol Content")
plt.xlabel("Alcohol")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()


# e) Bar Plot (Average alcohol by quality)
print("\n----- (e) Bar Plot: Average Alcohol by Wine Quality -----")

avg_alcohol = df.groupby('quality')['alcohol'].mean()

plt.figure()
avg_alcohol.plot(kind='bar')
plt.title("Average Alcohol Content by Wine Quality")
plt.xlabel("Wine Quality")
plt.ylabel("Average Alcohol")
plt.show()


# f) Boxplot
print("\n----- (f) Boxplot: Volatile Acidity across Wine Quality -----")

plt.figure()
sns.boxplot(x='quality', y='volatile acidity', data=df)
plt.title("Volatile Acidity Distribution by Wine Quality")
plt.show()


# g) Scatter Plot
print("\n----- (g) Scatter Plot: Alcohol vs Wine Quality -----")

plt.figure()
plt.scatter(df['alcohol'], df['quality'])
plt.title("Alcohol vs Wine Quality")
plt.xlabel("Alcohol")
plt.ylabel("Quality")
plt.show()


# h) Line Plot
print("\n----- (h) Line Plot: Average Sulphates by Wine Quality -----")

avg_sulphates = df.groupby('quality')['sulphates'].mean()

plt.figure()
plt.plot(avg_sulphates.index, avg_sulphates.values, marker='o')
plt.title("Average Sulphates by Wine Quality")
plt.xlabel("Wine Quality")
plt.ylabel("Average Sulphates")
plt.grid(True)
plt.show()


# i) One-Sample t-test
print("\n----- (i) One-Sample t-test for Alcohol -----")

t_stat, p_value = stats.ttest_1samp(df['alcohol'], 10)

print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Result: Mean alcohol is significantly different from 10%")
else:
    print("Result: Mean alcohol is NOT significantly different from 10%")


# j) Independent Sample t-test
print("\n----- (j) Independent Sample t-test -----")

group1 = df[df['quality'] >= 6]['alcohol']
group2 = df[df['quality'] < 6]['alcohol']

# Levene's test
lev_stat, lev_p = stats.levene(group1, group2)
print("Levene Test p-value:", lev_p)

t_stat, p_value = stats.ttest_ind(group1, group2, equal_var=(lev_p > 0.05))

print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Result: Significant difference in alcohol between groups")
else:
    print("Result: No significant difference in alcohol between groups")


# k) Paired Sample t-test
print("\n----- (k) Paired Sample t-test -----")

df['alcohol_increased'] = df['alcohol'] * 1.10

t_stat, p_value = stats.ttest_rel(df['alcohol'], df['alcohol_increased'])

print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Result: Significant difference after increasing alcohol")
else:
    print("Result: No significant difference")


# l) One-Way ANOVA
print("\n----- (l) One-Way ANOVA -----")

groups = [df[df['quality'] == q]['alcohol'] for q in df['quality'].unique()]

f_stat, p_value = stats.f_oneway(*groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Result: Alcohol differs significantly across quality levels")
else:
    print("Result: No significant difference across quality levels")


# m) Chi-Square Test
print("\n----- (m) Chi-Square Test -----")

# Create alcohol categories
df['alcohol_level'] = pd.cut(df['alcohol'],
                             bins=3,
                             labels=["Low", "Medium", "High"])

# Contingency table
cont_table = pd.crosstab(df['alcohol_level'], df['quality'])

print("Contingency Table:")
print(cont_table)

chi2, p, dof, expected = stats.chi2_contingency(cont_table)

print("Chi-square value:", chi2)
print("P-value:", p)

if p < 0.05:
    print("Result: Significant association between alcohol level and wine quality")
else:
    print("Result: No significant association between alcohol level and wine quality")

"""Overall structure:

1 Import libraries

2 Read dataset

3 df.head()

4 df.dtypes

5 Mean / Median / Mode

6 Variability (Range, IQR, STD, VAR)

7 Graphs
   - Histogram
   - Bar
   - Boxplot
   - Scatter
   - Line

8 Hypothesis Tests
   - One sample t
   - Independent t
   - Paired t
   - ANOVA
   - Chi-square

**Cheat sheet to understand and remember:**

**Import Libraries & Read Data**

**Step 1:** Always start with libraries → then read CSV.
Libraries are (Pandas, Numpy, Matplotlib, Seaborn, Scipy).

df = pd.read_csv(r"C:\Users\User\Documents\winequality.csv")


**Step 2: Check Data Types**
df.dtypes
dtypes → tells column types

**Step 3: Depending on the question asked do the task**

* Mean, Median, Mode

      df['alcohol'].mean()

      df['alcohol'].median()

      df['alcohol'].mode()[0] ------ #[0] selects the first mode value, otherwise mode() returns all mode values. Both are fine

* Variability Measures

Range → Max − Min

IQR → Q3 − Q1

      range_val = df['alcohol'].max() - df['alcohol'].min()
      iqr = df['alcohol'].quantile(0.75) - df['alcohol'].quantile(0.25)
      std = df['alcohol'].std()
      var = df['alcohol'].var()

* Histogram - Used for distribution

      plt.hist(df['alcohol'], bins=20)
      plt.show()

* Bar Plot (Group Mean)

      df.groupby('quality')['alcohol'].mean().plot(kind='bar')
      plt.show()
* Boxplot - Used for outliers & spread

sns.boxplot(x=category, y=value, data=df) -- this is the syntax

      sns.boxplot(x='quality', y='volatile acidity', data=df)   
      plt.show()

* Scatter Plot (Used for relationship between two variables)

plt.scatter(X , Y) --> syntax

    plt.scatter(df['alcohol'], df['quality'])
    plt.show()
* Line Plot

      avg = df.groupby('quality')['sulphates'].mean()

      plt.plot(avg.index, avg.values)
      plt.show()
* One Sample t-test ---Compare sample mean with fixed value
ttest_1samp(sample , population_mean) --->syntax

      stats.ttest_1samp(df['alcohol'], 10)

* Independent t-test (Compare two groups)

ttest_ind(group1 , group2) --> syntax

      group1 = df[df['quality']>=6]['alcohol']
      group2 = df[df['quality']<6]['alcohol']

      stats.ttest_ind(group1, group2)

* Paired t-test (Same data before/after)

ttest_rel(before , after) --> Syntax

    stats.ttest_rel(df['alcohol'], df['alcohol_increased'])

* One Way ANOVA (Compare more than 2 groups)

f_oneway(*groups) --> Syntax

    stats.f_oneway(group1, group2, group3)
* Chi-Square Test (Check relationship between categorical variables)

      table = pd.crosstab(df['alcohol_level'], df['quality'])

      stats.chi2_contingency(table)
"""